Repository depromeet/layer, pull requests merged in 2024-09, with the labels that each got.

#318 회고 생성으로 넘어올 때 spaceId 누락된 부분 수정
  src/component/retrospect/template/recommend/RecommendDone.tsx
Labels: ✌🏻 bugfix

#320 카카오 로그인 모바일 환경일 시 앱을 통한 로그인 구현
  index.html
  src/component/login/SocialLoginArea.tsx
  src/utils/etc.ts
Labels: ✌🏻 bugfix

#327 SDK를 적용한 카카오톡 앱 내 로그인 적용
  src/hooks/api/login/usePostKakaoToken.ts
Labels: ✌🏻 bugfix

#352 bottom 툴팁 애니메이션 수정
  apps/web/src/component/common/tip/Tooltip.tsx
Labels: ✌🏻 bugfix

#364 회고 생성 > 회고 마감일 설정 사용자 경험 개선 작업
  apps/web/src/assets/svgs/calendar/ic_next_chevron.svg
  apps/web/src/assets/svgs/calendar/ic_prev_chevron.svg
  apps/web/src/component/common/dateTimePicker/Calendar.tsx
  apps/web/src/component/common/dateTimePicker/TimePicker.tsx
  apps/web/src/component/common/dateTimePicker/time.const.ts
  apps/web/src/component/common/radioButton/Radio.tsx
  apps/web/src/component/common/radioButton/RadioButtonGroup.tsx
  apps/web/src/component/retrospectCreate/steps/DueDate.tsx
  apps/web/src/hooks/useRadioButton.ts
  apps/web/src/lib/provider/mix-pannel-provider/event.type.ts
  apps/web/src/types/retrospectCreate/index.ts
Labels: 🚀 improvement

#369 QA: 스페이스 뷰 QA 반영
  apps/web/src/app/home/RetrospectViewPage.tsx
  apps/web/src/component/common/tip/Tooltip.tsx
  apps/web/src/component/home/GoMakeReviewButton.tsx
  apps/web/src/component/space/view/EmptySpaceList.tsx
Labels: 🚀 feature

#382 QA) #381 기능 구현 및 개선
  apps/web/src/app/retrospect/template/recommend/RecommendSearch.tsx
  apps/web/src/app/space/CreateDonePage.tsx
  apps/web/src/component/space/create/CreateSpace.tsx
  apps/web/src/component/space/create/Thumb.tsx
  apps/web/src/component/space/members/MemberInviteModal.tsx
  apps/web/src/component/space/members/MembersList.tsx
  apps/web/src/component/space/view/SpaceCountView.tsx
  apps/web/src/hooks/api/space/useApiUploadImage.ts
  apps/web/src/store/space/spaceAtom.ts
  apps/web/src/types/space.ts
Labels: 🚀 feature

#384 스페이스 이름에 맞는 조사 적용 함수
  apps/web/src/app/retrospect/template/recommend/RecommendSearch.tsx
  apps/web/src/utils/retrospect/chooseParticle.ts
Labels: 🚀 feature

#385 스페이스 상세뷰 - 분석 뷰까지의 로직 생성
  apps/web/src/api/index.ts
  apps/web/src/app/info/PrivacyPolicyPage.tsx
  apps/web/src/app/info/TermsOfServicePage.tsx
  apps/web/src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
  apps/web/src/app/space/SpaceViewPage.tsx
  apps/web/src/component/common/empty/EmptyList.tsx
  apps/web/src/component/retrospect/analysis/Analysis.tsx
  apps/web/src/component/space/view/ProceedingTextBox.tsx
  apps/web/src/component/space/view/RetrospectBox.tsx
  apps/web/src/component/space/view/RetrospectEditModal.tsx
  apps/web/src/component/space/view/RetrospectOptions.tsx
  apps/web/src/config/info.ts
  apps/web/src/hooks/api/analysis/useApiGetAnalysis.ts
  apps/web/src/hooks/api/retrospect/analysis/useGetAnalysisAnswer.ts
  apps/web/src/hooks/api/retrospect/edit/usePatchRetrospect.ts
  apps/web/src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
  apps/web/src/types/retrospect/index.ts
  apps/web/src/utils/date/index.ts
Labels: 🚀 feature

#387 Readme.md 파일 생성
  readme.md
Labels: 📓 documentation

#398 분석 페이지 포인트가 없을시 조건 추가
  apps/web/src/component/home/SummaryInsightBox.tsx
Labels: 🫨 bug
