Repository depromeet/layer, pull requests merged in 2024-07, with the labels that each got.

#3 Feature/#1/emotion
  .babelrc
  package.json
  pnpm-lock.yaml
  tsconfig.json
  vite.config.ts
Labels: 📚 setting

#5 chore/#1/build 자동화 workflow
  .github/workflows/build-test.yml
Labels: 📚 setting

#4 Feature/#1/Tanstack Query, Jotai 환경 설정 (+ devtools)
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/app.tsx
  src/app/MainPage.tsx
  src/lib/tanstack-query/queryClient.ts
  src/main.tsx
  src/router/index.tsx
  src/store/messageAtom.tsx
  vite.config.ts
Labels: 📚 setting

#7 fix/1/build workflow 문법 오류 수정
  .github/workflows/build-test.yml
Labels: ✌🏻 bugfix

#9 chore: #1 포크의 경우 main브랜치 이름 추가
  .github/workflows/build-test.yml
  src/app/MainPage.tsx
Labels: ✌🏻 bugfix

#10 chore: #1 modify package.json version (snapshot)
  package.json
Labels: 📚 setting

#8 Feature/#1/kakao social login setting
  src/app/login/KakaoLogin.tsx
  src/app/login/KakaoLoginRedirection.tsx
Labels: 📚 setting

#13 feat: #12 Add Common Layout Definition
  src/app/login/KakaoLoginRedirection.tsx
  src/layout/default.tsx
  src/style/global.css
Labels: 🚀 feature

#14 chore: #1 build workflow develop 추가, pull_request_target 원복
  .github/workflows/build-test.yml
Labels: 📚 setting

#15 개발 서버 환경을 위한 새로운 워크플로우 추가
  .github/workflows/workflow-dev.yml
Labels: 📚 setting

#16 워크플로우 추가를 위한 메인 병합
  .github/workflows/build-test.yml
  .github/workflows/workflow-dev.yml
  src/app/login/KakaoLoginRedirection.tsx
  src/layout/default.tsx
  src/style/global.css
Labels: 📚 setting

#17 공통 컴포넌트 프로그래스 바 개발
  src/app/test/Staging.tsx
  src/component/ProgressBar/ProgressBar.tsx
  src/router/index.tsx
  src/style/global.css
  vercel.json
Labels: 🚀 feature

#20 Feat/#11/social login button
  src/assets/imgs/loginLogo.svg
  src/component/Img/LoginSpriteSvg.tsx
  src/component/button/SocialLoginButton.tsx
  src/style/global.css
  src/types/loginType/index.tsx
Labels: 🚀 feature

#21 Feature/2/커스텀 라디오 버튼
  src/component/common/Card/ListItemCard.tsx
  src/component/common/RadioButton/Radio.tsx
  src/component/common/RadioButton/RadioButtonGroup.tsx
  src/store/context/RadioContext.ts
Labels: 🚀 feature

#22 Feat/11/modal component
  index.html
  src/app/MainPage.tsx
  src/component/common/modal/Modal.tsx
  src/component/common/modal/ModalPortal.tsx
  src/hooks/useModal.ts
  src/store/modal/modalAtom.ts
  src/types/modal.ts
Labels: 🚀 feature

#23 단일 · 다중 버튼 컴포넌트 개발
  src/app/test/Staging.tsx
  src/component/Button/Button.tsx
  src/component/Button/ButtonProvider.tsx
  src/layout/DefaultLayout.tsx
  src/layout/GlobalLayout.tsx
  src/layout/default.tsx
  src/router/index.tsx
Labels: 🚀 feature

#25 Feature/11/icon component
  src/app/MainPage.tsx
  src/assets/react.svg
  src/assets/svgs/common/ic_back.svg
  src/assets/svgs/common/ic_check.svg
  src/assets/svgs/common/index.ts
  src/assets/svgs/index.ts
  src/assets/svgs/toast/ic_success.svg
  src/assets/svgs/toast/index.ts
  src/component/common/Icon/Icon.tsx
  src/svg.d.ts
Labels: 🚀 feature

#30 Typography Component 개발
  src/component/common/typography/index.tsx
  src/style/variable.ts
Labels: 🚀 feature

#24 AppBar Component 개발
  pnpm-lock.yaml
  src/app/login/Login.tsx
  src/app/login/google/googleLogin.tsx
  src/app/login/kakao/KakaoLoginRedirection.tsx
  src/app/login/kakao/kakaoLogin.tsx
  src/component/common/Icon/Icon.tsx
  src/component/common/appBar/index.tsx
  src/layout/DefaultLayout.tsx
  src/router/index.tsx
Labels: 🚀 feature

#32 Input, Label 공통 컴포넌트 개발 (+ 컨테이너, 훅)
  src/app/test/Staging.tsx
  src/component/common/Input/Input.tsx
  src/component/common/Input/InputLabelContainer.tsx
  src/component/common/Input/Label.tsx
  src/component/common/Input/index.ts
  src/hooks/useInput.ts
  src/style/global.css
Labels: 🚀 feature

#36 Refactor/28/convention refactor
  src/app/login/KakaoLoginRedirection.tsx
  src/app/login/Login.tsx
  src/app/login/LoginPage.tsx
  src/app/login/google/googleLogin.tsx
  src/app/login/kakao/kakaoLogin.tsx
  src/assets/svgs/spriteSvgs/loginLogo.svg
  src/component/Img/LoginSpriteSvg.tsx
  src/component/common/appBar/index.tsx
  src/component/common/typography/index.tsx
  src/component/login/loginSpriteSvg/index.tsx
  src/component/login/socialLoginButton/index.tsx
  src/layout/DefaultLayout.tsx
  src/router/index.tsx
  src/svg.d.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
Labels: 🧹 refactor

#34 토스트 메세지 컴포넌트 개발
  .eslintrc.cjs
  index.html
  src/app/MainPage.tsx
  src/component/common/Icon/Icon.tsx
  src/component/common/Modal/Modal.tsx
  src/component/common/Portal/Portal.tsx
  src/component/common/Toast/Toast.tsx
  src/component/common/Toast/ToastItem.tsx
  src/component/common/modal/ModalPortal.tsx
  src/hooks/useModal.ts
  src/hooks/useToast.ts
  src/store/modal/modalAtom.ts
  src/store/toast/toastAtom.ts
  src/style/common/animation.ts
  src/style/common/toast.ts
  src/types/toast.ts
  src/util/etc.ts
  src/util/toast/collapseToast.ts
Labels: 🚀 feature

#43 컨벤션 적용
  src/app/MainPage.tsx
  src/component/common/Icon/Icon.tsx
  src/component/common/Icon/index.ts
  src/component/common/Modal/Modal.tsx
  src/component/common/Modal/index.ts
  src/component/common/Portal/index.ts
  src/component/common/Toast/Toast.tsx
  src/component/common/Toast/ToastItem.tsx
  src/component/common/Toast/index.ts
  src/component/common/appBar/AppBar.tsx
Labels: 🧹 refactor

#33 바텀시트 컴포넌트 개발
  index.html
  package.json
  pnpm-lock.yaml
  src/app.tsx
  src/app/test/Staging.tsx
  src/assets/svgs/bottom-sheet/ic_quit.svg
  src/assets/svgs/bottom-sheet/index.ts
  src/assets/svgs/index.ts
  src/component/BottomSheet/BottomSheet.tsx
  src/component/BottomSheet/BottomSheetOption.ts
  src/component/BottomSheet/component/BottomSheetContent.tsx
  src/component/BottomSheet/component/BottomSheetHeader.tsx
  src/component/BottomSheet/component/index.ts
  src/component/BottomSheet/index.ts
  src/hooks/useBottomSheet.ts
  src/utils/.gitkeep
  src/utils/externalStore/create.ts
  src/utils/externalStore/hook.ts
Labels: 🚀 feature

#47 Input, TextArea 글자 수 카운트 추가
  src/app/test/Staging.tsx
  src/component/common/input/Input.tsx
  src/component/common/input/TextArea.tsx
  src/component/common/input/index.ts
  src/hooks/useCheckBox.ts
  src/hooks/useInput.ts
  src/hooks/useRadioButton.ts
  src/style/global.css
  src/style/variable.ts
Labels: 🚀 feature

#50 TipCard 컴포넌트 작성
  src/component/common/tip/TipCard.tsx
  src/style/variable.ts
Labels: 🚀 feature

#54 Typography children 타입 수정
  src/component/common/typography/Typography.tsx
Labels: ✌🏻 bugfix

#55 Kakao Login Logic 생성
  package.json
  src/api/index.ts
  src/api/login/index.ts
  src/app/login/KakaoLoginRedirection.tsx
  src/app/login/LoginPage.tsx
  src/app/login/SetNicknamePage.tsx
  src/layout/RequireLoginLayout.tsx
  src/router/index.tsx
  src/store/auth/authAtom.tsx
  src/types/loginType/index.tsx
Labels: 🚀 feature

#57 스페이스 생성 뷰 개발
  .gitignore
  pnpm-lock.yaml
  src/api/login/index.ts
  src/app/space/CreateDonePage.tsx
  src/app/space/CreateInvitePage.tsx
  src/app/space/CreateSpacePage.tsx
  src/assets/imgs/profile.jpeg
  src/assets/svgs/common/ic_arrow_left.svg
  src/assets/svgs/common/index.ts
  src/assets/svgs/index.ts
  src/assets/svgs/space/ic_earth.svg
  src/assets/svgs/space/ic_earth_re.svg
  src/assets/svgs/space/ic_flask.svg
  src/assets/svgs/space/ic_human.svg
  src/assets/svgs/space/ic_space_chart.svg
  src/assets/svgs/space/index.ts
  src/component/common/Icon/Icon.tsx
  src/component/space/CategoryButton.tsx
  src/component/space/FieldButton.tsx
  src/component/space/create/Category.tsx
  src/component/space/create/CreateSpace.tsx
  src/component/space/create/Field.tsx
  src/component/space/create/Home.tsx
  src/component/space/create/Info.tsx
  src/component/space/create/Thumb.tsx
  src/component/space/field.const.ts
  src/component/space/index.ts
  src/hooks/api/space/useApiPostSpace.ts
  src/router/index.tsx
  src/store/space/spaceAtom.ts
  src/types/space.ts
Labels: 🚀 feature
