Repository depromeet/layer, pull requests merged in 2024-08, with the labels that each got.

#60 스페이스 생성 이미지 업로드 기능 로직 수정
  src/app/space/CreateSpacePage.tsx
  src/assets/svgs/common/ic_copy.svg
  src/assets/svgs/common/ic_kakao.svg
  src/component/space/create/CreateSpace.tsx
  src/component/space/create/Field.tsx
  src/component/space/create/Thumb.tsx
  src/component/space/space.const.ts
  src/router/index.tsx
  src/types/space.ts
Labels: 🧹 refactor

#62 회고 생성 API 연동
  pnpm-lock.yaml
  src/app.tsx
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/app/retrospectCreate/RetrospectCreateComplete.tsx
  src/app/space/CreateDonePage.tsx
  src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
  src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/component/retrospectCreate/dueDate/DateTimePicker.tsx
  src/component/retrospectCreate/steps/CustomTemplate.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
  src/component/retrospectCreate/steps/MainInfo.tsx
  src/config/paths.ts
  src/hooks/api/retrospect/create/usePostRetrospectCreate.ts
  src/hooks/api/retrospectCreate/usePostRetrospectCreate.ts
  src/hooks/api/space/useApiPostSpace.ts
  src/hooks/api/space/useGetSpace.ts
  src/hooks/api/template/useGetCustomTemplate.ts
  src/hooks/useFullModal.ts
  src/hooks/useMultiStepForm.ts
  src/store/retrospect/retrospectCreate.ts
  src/types/retrospectCreate/index.ts
  src/types/space.ts
  src/types/template.ts
  src/utils/formatDate.ts
Labels: 🚀 feature, 🧹 refactor

#63 회고 생성 시 필수 질문 자동 삽입, 홈 라우터 수정
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/home/NavigaionBar.tsx
  src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/component/retrospectCreate/customTemplate/questions.const.ts
  src/config/paths.ts
  src/layout/HomeLayout.tsx
  src/router/index.tsx
Labels: ✌🏻 bugfix

#58 스페이스 전체 뷰 페이지 개발 및 로그인 로직 수정
  .gitignore
  pnpm-lock.yaml
  src/api/login/index.ts
  src/app/home/RetrospectViewPage.tsx
  src/app/login/KakaoLoginRedirection.tsx
  src/app/space/SpaceViewPage.tsx
  src/assets/svgs/common/ic_3point.svg
  src/assets/svgs/common/ic_after.svg
  src/assets/svgs/common/ic_arrowLeft.svg
  src/assets/svgs/common/ic_clock.svg
  src/assets/svgs/common/ic_cylinder.svg
  src/assets/svgs/common/ic_earth.svg
  src/assets/svgs/common/ic_file.svg
  src/assets/svgs/common/ic_folder.svg
  src/assets/svgs/common/ic_list.svg
  src/assets/svgs/common/ic_stars.svg
  src/assets/svgs/common/ic_team.svg
  src/assets/svgs/common/ic_writePen.svg
  src/assets/svgs/common/index.ts
  src/assets/svgs/space/ic_earth.svg
  src/assets/svgs/space/index.ts
  src/component/common/Modal/MidModal.tsx
  src/component/common/Toast/Toast.tsx
  src/component/common/appBar/AppBar.tsx
  src/component/common/typography/Typography.tsx
  src/component/home/SpaceOverview.tsx
  src/component/home/TagBox.tsx
  src/component/home/ViewSelectTab.tsx
  src/component/home/index.ts
  src/component/space/CreateRetrospectiveSheet.tsx
  src/component/space/index.ts
  src/component/space/view/EmptyRetrospect.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/component/space/view/SpaceCountView.tsx
  src/component/space/view/TeamGoalView.tsx
  src/hooks/api/retrospect/useSpaceRetrospects.ts
  src/hooks/api/space/useApiDeleteSpace.ts
  src/hooks/api/space/useApiGetSpaceInfo.ts
  src/hooks/api/space/useApiGetSpaceList.ts
  src/router/index.tsx
  src/style/variable.ts
  src/types/spaceType/index.ts
Labels: 🚀 feature

#64 fix: #35 회고 생성 시 필수질문 앞에 오도록
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/store/retrospect/retrospectCreate.ts
  src/types/retrospectCreate/index.ts
Labels: ✌🏻 bugfix

#67 스페이스 아이디 history state 형태 안 맞는 문제 해결
  src/app/space/CreateNextPage.tsx
  src/router/index.tsx
Labels: ✌🏻 bugfix

#71 타임피커 스크롤 문제 수정
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/common/button/ButtonProvider.tsx
  src/component/common/radioButton/RadioButtonGroup.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
Labels: ✌🏻 bugfix

#74 회고 생성 수정된 UI/UX 반영
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/app/retrospectCreate/RetrospectCreateComplete.tsx
  src/assets/svgs/index.ts
  src/assets/svgs/retrospect/ic_calendar.svg
  src/assets/svgs/retrospect/ic_notebook.svg
  src/assets/svgs/retrospect/ic_notebook_open.svg
  src/assets/svgs/retrospect/ic_star.svg
  src/assets/svgs/retrospect/index.ts
  src/component/common/Card/Card.tsx
  src/component/common/Modal/FullModal.tsx
  src/component/common/Spacing/Spacing.tsx
  src/component/common/Toast/Toast.tsx
  src/component/common/button/ButtonProvider.tsx
  src/component/common/radioButton/RadioButtonGroup.tsx
  src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
  src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/component/retrospectCreate/customTemplate/OrderLabel.tsx
  src/component/retrospectCreate/customTemplate/QuestionItemCheckbox.tsx
  src/component/retrospectCreate/dueDate/DateTimePicker.tsx
  src/component/retrospectCreate/steps/CustomTemplate.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
  src/component/retrospectCreate/steps/Start.tsx
  src/component/write/modal/TemporarySaveModal.tsx
  src/hooks/useDateTimePicker.ts
  src/hooks/useEditQuestions.ts
  src/store/retrospect/retrospectCreate.ts
  src/store/templateAtom.ts
  src/style/calendar.css
  src/style/variable.ts
  src/types/template.ts
  src/utils/formatDate.ts
Labels: 🚀 feature, 🧹 refactor

#77 회고 생성 날짜, 모달 버튼 배경 관련 버그 수정
  src/component/common/Modal/FullModal.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
Labels: ✌🏻 bugfix

#81 Sprite 이미지 크로스 브라우징 이슈 해결
  src/assets/svgs/spriteSvgs/loginLogo.svg
  src/component/login/LoginSpriteSvg.tsx
Labels: 🫨 bug

#78 Feat/35/design update
  src/app/home/RetrospectViewPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/assets/svgs/common/ic_bluePoint.svg
  src/assets/svgs/common/ic_calendar.svg
  src/assets/svgs/common/ic_clock.svg
  src/assets/svgs/common/ic_darkPerson.svg
  src/assets/svgs/common/ic_more.svg
  src/assets/svgs/common/ic_person.svg
  src/assets/svgs/common/ic_plus.svg
  src/assets/svgs/common/ic_template.svg
  src/assets/svgs/common/ic_twoMan.svg
  src/assets/svgs/common/index.ts
  src/component/common/input/TextArea.tsx
  src/component/common/typography/Typography.tsx
  src/component/space/CreateRetrospectiveSheet.tsx
  src/component/space/index.ts
  src/component/space/view/ActionItemListView.tsx
  src/component/space/view/EmptyRetrospect.tsx
  src/component/space/view/LoadingSpinner.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/RetrospectButton.tsx
  src/component/space/view/RetrospectOptions.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/component/space/view/SpaceCountView.tsx
  src/component/space/view/TeamGoalView.tsx
  src/config/paths.ts
  src/hooks/api/actionItem/useApiOptionsGetTeamActionItemList.ts
  src/hooks/api/actionItem/useApiPostActionItem.ts
  src/hooks/api/retrospect/useApiDeleteRetrospect.ts
  src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
  src/hooks/api/space/useApiDeleteSpace.ts
  src/hooks/api/space/useApiGetSpaceList.ts
  src/hooks/api/space/useApiOptionsGetSpaceInfo.ts
  src/layout/DefaultLayout.tsx
  src/router/index.tsx
  src/style/variable.ts
  src/types/actionItem/index.ts
Labels: 🚀 feature

#80 디자인 토큰 추가
  src/style/designTokens.ts
  src/style/variable.ts
Labels: 📚 setting

#86 템플릿 수정 후 뒤로갔을 때 질문 리스트가 다시 뜨도록 수정
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/assets/svgs/common/ic_calendar.svg
  src/assets/svgs/retrospect/ic_calendar.svg
  src/assets/svgs/retrospect/index.ts
  src/component/retrospectCreate/steps/CustomTemplate.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
  src/config/paths.ts
  src/hooks/useMultiStepForm.ts
  src/store/retrospect/retrospectCreate.ts
Labels: ✌🏻 bugfix, 🧹 refactor

#97 회고 생성 스크롤 문제 수정
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/retrospectCreate/customTemplate/ConfirmDefaultTemplate.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
  src/component/retrospectCreate/steps/MainInfo.tsx
  src/component/retrospectCreate/steps/Start.tsx
Labels: ✌🏻 bugfix

#104 템플릿 리스트 조회 개발, 회고 생성 연결
  src/app.tsx
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/app/space/CreateNextPage.tsx
  src/assets/svgs/template/ic_info.svg
  src/assets/svgs/template/index.ts
  src/component/common/Card/Card.tsx
  src/component/common/button/Button.tsx
  src/component/common/skeleton/SkeletonCard.tsx
  src/component/common/tabs/TabButton.tsx
  src/component/common/tabs/Tabs.tsx
  src/component/common/tabs/TagButton.tsx
  src/component/common/tag/Tag.tsx
  src/component/retrospect/template/list/CustomTemplateList.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
  src/component/retrospect/template/list/DefaultTemplateListItem.tsx
  src/component/retrospect/template/list/index.ts
  src/component/retrospectCreate/customTemplate/AddOptionTabs.tsx
  src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
  src/component/retrospectCreate/customTemplate/index.ts
  src/component/retrospectCreate/steps/CustomTemplate.tsx
  src/component/space/CreateRetrospectiveSheet.tsx
  src/hooks/api/template/useGetCustomTemplate.ts
  src/hooks/api/template/useGetCustomTemplateList.ts
  src/hooks/api/template/useGetDefaultTemplateList.ts
  src/hooks/useIntersectionObserve.ts
  src/layout/DualToneLayout.tsx
  src/router/index.tsx
  src/style/common/animation.ts
  src/style/designTokens.ts
  src/types/pagination.ts
  src/types/template.ts
Labels: 🚀 feature, 🧹 refactor

#106 Design/88/design system sean
  src/app/home/RetrospectViewPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/common/Modal/MidModal.tsx
  src/component/common/appBar/AppBar.tsx
  src/component/common/typography/Typography.tsx
  src/component/home/GoMakeReviewButton.tsx
  src/component/home/NavigaionBar.tsx
  src/component/home/SpaceOverview.tsx
  src/component/home/TagBox.tsx
  src/component/home/ViewSelectTab.tsx
  src/component/login/LoginCarousel.tsx
  src/component/login/SocialLoginButton.tsx
  src/component/space/view/ActionItemListView.tsx
  src/component/space/view/EmptyRetrospect.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/RetrospectButton.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/component/space/view/SpaceCountView.tsx
  src/layout/DefaultLayout.tsx
  src/style/designTokens.ts
  src/types/loginType/index.tsx
Labels: 🚀 feature

#108 Input 에러 메시지 maxLength 조건 수정
  src/component/common/input/Input.tsx
  src/hooks/useValidation.ts
Labels: ✌🏻 bugfix

#110 앱바 높이 변수 처리에 따른 수정 + DualToneLayout 버그 수정
  src/app/space/SpaceViewPage.tsx
  src/component/common/appBar/AppBar.tsx
  src/layout/DefaultLayout.tsx
  src/layout/DualToneLayout.tsx
  src/style/global.css
Labels: ✌🏻 bugfix, 🧹 refactor

#112 회고 생성 플로우 수정, 페이지 이탈 시 템플릿 임시저장
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/common/input/TextArea.tsx
  src/component/retrospectCreate/customTemplate/AddQuestionsBottomSheet.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/component/retrospectCreate/steps/CustomTemplate.tsx
  src/component/retrospectCreate/steps/DueDate.tsx
  src/component/retrospectCreate/steps/Start.tsx
  src/hooks/api/template/usePostRecentTemplateId.ts
  src/store/retrospect/retrospectCreate.ts
  src/store/templateAtom.ts
Labels: 🚀 feature, ✌🏻 bugfix

#114 유저 정보 페이지 2차 개발 완료
  src/app/info/FeedBackPage.tsx
  src/app/info/HelpPage.tsx
  src/app/info/LicensePage.tsx
  src/app/info/NoticePage.tsx
  src/app/info/PrivacyPolicyPage.tsx
  src/app/info/TermsOfServicePage.tsx
  src/component/info/ServicePolicyBox.tsx
  src/component/info/VersionBox.tsx
  src/config/info.ts
  src/config/paths.ts
  src/router/index.tsx
Labels: 🚀 feature

#90 animation 수정 및 getUser api hook 추가
  src/app/space/CreateDonePage.tsx
  src/app/space/CreateSpacePage.tsx
  src/hooks/api/auth/useApiGetUser.ts
Labels: 🚀 feature, 🧹 refactor

#125 템플릿 수정, 삭제 기능 개발 (+ DropdownMenu)
  index.html
  package.json
  pnpm-lock.yaml
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/assets/svgs/common/ic_more.svg
  src/component/common/dropdownMenu/DropdownMenu.tsx
  src/component/retrospect/template/list/CustomTemplateList.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
  src/component/retrospect/template/list/DefaultTemplateListItem.tsx
  src/component/space/view/RetrospectOptions.tsx
  src/hooks/api/template/useDeleteCustomTemplate.ts
  src/hooks/api/template/usePatchTemplateTitle.ts
Labels: 🚀 feature

#127 auth가 필요한 페이지 로그인 후 리다이렉트
  src/component/space/join/JoinSpace.tsx
  src/config/storage-keys.ts
  src/hooks/api/login/usePostSignIn.ts
  src/layout/RequireLoginLayout.tsx
  src/router/index.tsx
Labels: ✌🏻 bugfix

#130 Tabs 컴포넌트 배경 부모 색 적용
  src/app/home/GoalViewPage.tsx
  src/component/common/tabs/Tabs.tsx
Labels: ✌🏻 bugfix

#121 웹뷰 세팅 && 브릿지 모듈 추가
  package.json
  pnpm-lock.yaml
  src/app.tsx
  src/layout/GlobalLayout.tsx
  src/lib/create-context/index.tsx
  src/lib/provider/bridge-provider.tsx
  src/link-bridge/index.ts
  src/link-bridge/native.ts
Labels: 👋🏻 Good first issue

#136 대표템플릿 저장 및 불러오기 로직 반영
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/app/retrospectCreate/RetrospectCreateComplete.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/space/CreateRetrospectiveSheet.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/hooks/useMultiStepForm.ts
Labels: 🚀 feature

#138 DateTimePicker 공통 컴포넌트로 분리
  package.json
  pnpm-lock.yaml
  src/app/retrospectCreate/RetrospectCreate.tsx
  src/component/common/dateTimePicker/Calendar.tsx
  src/component/common/dateTimePicker/DateTimePicker.tsx
  src/component/common/dateTimePicker/TimePicker.tsx
  src/component/common/dateTimePicker/index.ts
  src/component/common/dateTimePicker/time.const.ts
  src/component/common/input/DateTimeInput.tsx
  src/component/common/input/index.ts
  src/component/common/radioButton/Radio.tsx
  src/component/retrospectCreate/dueDate/DateTimePicker.tsx
  src/component/retrospectCreate/index.ts
  src/component/retrospectCreate/steps/DueDate.tsx
  src/hooks/api/retrospect/create/usePostRetrospectCreate.ts
  src/hooks/useDateTimePicker.ts
  src/hooks/useMultiStepForm.ts
  src/store/retrospect/retrospectCreate.ts
Labels: ✌🏻 bugfix, 🧹 refactor

#142 스페이스 뷰 페이지 1차 변경 및 리팩토링
  src/app/space/SpaceViewPage.tsx
  src/component/home/TagBox.tsx
  src/component/space/view/ActionItemListView.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/component/space/view/SpaceCountView.tsx
  src/hooks/api/actionItem/useApiPostActionItem.ts
  src/layout/DualToneLayout.tsx
  src/types/spaceType/index.ts
  src/utils/space/categoryTagKoreanChange.ts
Labels: ✌🏻 bugfix

#145 회고 수정 및 삭제
  pnpm-lock.yaml
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/common/dateTimePicker/DateTimePicker.tsx
  src/component/common/input/DateTimeInput.tsx
  src/component/common/radioButton/Radio.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/RetrospectEditModal.tsx
  src/component/space/view/RetrospectOptions.tsx
  src/hooks/api/retrospect/edit/usePatchRetrospect.ts
  src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
  src/hooks/useDateTimePicker.ts
  src/hooks/useRadioButton.ts
  src/hooks/useRequiredParams.ts
  src/utils/formatDate.ts
Labels: 🚀 feature

#149 툴팁 공통 컴포넌트
  index.html
  src/component/common/tip/Tooltip.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/style/common/animation.ts
  src/style/common/bounce.ts
Labels: ✌🏻 bugfix, 🧹 refactor

#152 회고 생성 템플릿 리스트의 경우 옵션 버튼 제거
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/component/retrospect/template/list/CustomTemplateList.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
  src/component/retrospect/template/list/DefaultTemplateListItem.tsx
  src/component/retrospect/template/list/index.ts
Labels: ✌🏻 bugfix

#154 상세 디테일 버그 수정
  src/app/home/RetrospectViewPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/assets/svgs/space/icon_file_open.svg
  src/assets/svgs/space/index.ts
  src/component/home/SpaceOverview.tsx
  src/component/space/view/ActionItemListView.tsx
  src/component/space/view/RetrospectBox.tsx
  src/utils/space/categoryTagKoreanChange.ts
Labels: 🚀 feature, ✌🏻 bugfix

#159 기타 에러 수정
  src/assets/svgs/common/ic_bluePoint.svg
  src/component/info/UserBox.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/hooks/api/space/useApiDeleteSpace.ts
Labels: ✌🏻 bugfix

#157 템플릿 추천 기능 구현
  src/app/retrospect/template/recommend/RecommendDonePage.tsx
  src/app/retrospect/template/recommend/RecommendTemplatePage.tsx
  src/assets/svgs/retrospect/ic_irRegular_color.svg
  src/assets/svgs/retrospect/ic_irRegular_white.svg
  src/assets/svgs/retrospect/ic_regular_color.svg
  src/assets/svgs/retrospect/ic_regular_white.svg
  src/component/common/button/CategoryButton.tsx
  src/component/common/button/FieldButton.tsx
  src/component/common/button/index.ts
  src/component/common/tip/Tooltip.tsx
  src/component/retrospect/template/card/TemplateCard.tsx
  src/component/retrospect/template/recommend/Period.tsx
  src/component/retrospect/template/recommend/Periodic.tsx
  src/component/retrospect/template/recommend/Purpose.tsx
  src/component/retrospect/template/recommend/RecommendDone.tsx
  src/component/retrospect/template/recommend/RecommendTemplate.tsx
  src/component/retrospect/template/recommend/recommend.const.ts
  src/component/space/CreateRetrospectiveSheet.tsx
  src/component/space/create/Category.tsx
  src/component/space/create/CreateSpace.tsx
  src/component/space/create/Field.tsx
  src/component/space/index.ts
  src/config/paths.ts
  src/hooks/api/retrospect/recommend/useApiRecommendTemplate.ts
  src/router/index.tsx
  src/store/retrospect/template/recommend/recommendAtom.ts
  src/types/retrospectCreate/recommend.ts
Labels: 🚀 feature

#162 스페이스 상세 액션아이템 추가 및 추가 시 상세페이지 반영
  src/app/space/SpaceViewPage.tsx
  src/component/space/view/ActionItemListView.tsx
Labels: 🚀 feature

#163 TimePicker 사파리 이슈 해결
  src/hooks/useDateTimePicker.ts
Labels: ✌🏻 bugfix

#165 툴팁 꼬리 위치 고정 값으로 수정
  src/component/common/tip/Tooltip.tsx
  src/component/retrospect/template/recommend/RecommendDone.tsx
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
Labels: ✌🏻 bugfix

#164 스페이스 수정 버튼 임시 로직
  src/component/space/view/SpaceAppBarRightComp.tsx
Labels: 🚀 feature

#166 회고 생성 isPending LoadingModal 추가
  src/app/retrospectCreate/RetrospectCreate.tsx
Labels: 🚀 feature

#167 DateTimePicker 시간 선택 안 한 경우 0시
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/space/CreateRetrospectiveSheet.tsx
  src/config/paths.ts
  src/hooks/useDateTimePicker.ts
Labels: ✌🏻 bugfix

#168 대표 템플릿 연결
  src/app/space/SpaceViewPage.tsx
  src/component/space/view/SpaceCountView.tsx
  src/types/spaceType/index.ts
Labels: 🚀 feature

#171 대표템플릿 태그 이름 출력
  pnpm-lock.yaml
  src/component/space/view/SpaceCountView.tsx
Labels: ✌🏻 bugfix

#173 스페이스 생성 완료 후 추천 페이지로 이동
  src/app/space/CreateNextPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/retrospect/template/recommend/RecommendDone.tsx
  src/router/index.tsx
Labels: ✌🏻 bugfix

#183 애플로그인 구현
  index.html
  src/app/login/LoginPage.tsx
  src/component/login/SocialLoginButton.tsx
  src/types/loginType/index.tsx
  src/vite-env.d.ts
Labels: 🚀 feature

#192 DateTimePicker 반환값 timezone offset 제거
  src/hooks/useDateTimePicker.ts
Labels: ✌🏻 bugfix

#208 템플릿 리스트 - 템플릿 상세 - 회고 생성 관련 라우팅
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/app/template/TemplatePage.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
  src/component/retrospect/template/list/DefaultTemplateListItem.tsx
  src/component/space/CreateRetrospectiveSheet.tsx
Labels: ✌🏻 bugfix

#206 부분 SSR 테스트
  src/api/server.cjs
Labels: 🚧 still working

#218 템플릿 리스트 빈 화면 추가
  src/app/retrospect/template/list/TemplateListPage.tsx
  src/component/common/dropdownMenu/DropdownMenu.tsx
  src/component/common/empty/EmptyList.tsx
  src/component/common/empty/index.ts
  src/component/retrospect/template/list/CustomTemplateList.tsx
  src/component/retrospect/template/list/CustomTemplateListItem.tsx
Labels: 🚀 feature, ✌🏻 bugfix

#216 분석 개발 완료 (일부 제외)
  package.json
  pnpm-lock.yaml
  src/app/info/UserDeletion.tsx
  src/app/login/LoginPage.tsx
  src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
  src/assets/lottie/login/login_carousel_1.json
  src/assets/lottie/login/login_carousel_2.json
  src/assets/lottie/login/login_carousel_3.json
  src/assets/lottie/login/login_carousel_4.json
  src/assets/svgs/analysis/Check_Filled.svg
  src/assets/svgs/analysis/ic_bad_mark.svg
  src/assets/svgs/analysis/ic_dissatisfied.svg
  src/assets/svgs/analysis/ic_good_mark.svg
  src/assets/svgs/analysis/ic_improve_mark.svg
  src/assets/svgs/analysis/ic_neutral.svg
  src/assets/svgs/analysis/ic_satisfied.svg
  src/assets/svgs/analysis/ic_very_dissatisfied.svg
  src/assets/svgs/analysis/ic_very_satisfied.svg
  src/assets/svgs/analysis/index.ts
  src/assets/svgs/common/ic_bluePoint.svg
  src/assets/svgs/common/ic_twoMan_blue.svg
  src/assets/svgs/common/index.ts
  src/assets/svgs/index.ts
  src/component/info/UserManageBox.tsx
  src/component/login/LoginCarousel.tsx
  src/component/retrospect/analysis/Analysis.tsx
  src/component/retrospect/analysis/GoalCompletionRateChart.tsx
  src/component/retrospect/analysis/InsightsBoxSection.tsx
  src/component/retrospect/analysis/TeamSatisfactionChart.tsx
  src/hooks/api/analysis/useApiGetAnalysis.ts
  src/style/designTokens.ts
  src/types/analysis/index.ts
Labels: 🚀 feature

#219 맴버 관리 페이지 개발
  src/app/retrospect/template/recommend/RecommendTemplatePage.tsx
  src/app/space/members/MembersEditListPage.tsx
  src/app/space/members/MembersListPage.tsx
  src/assets/svgs/common/ic_copy.svg
  src/assets/svgs/space/ic_crown.svg
  src/assets/svgs/space/index.ts
  src/component/common/Toast/Toast.tsx
  src/component/common/button/IconButton.tsx
  src/component/common/dropdownMenu/DropdownMenu.tsx
  src/component/retrospect/template/recommend/RecommendDone.tsx
  src/component/space/members/MemberInviteModal.tsx
  src/component/space/members/MembersEditList.tsx
  src/component/space/members/MembersItem.tsx
  src/component/space/members/MembersList.tsx
  src/component/space/view/SpaceAppBarRightComp.tsx
  src/component/space/view/SpaceCountView.tsx
  src/hooks/api/space/members/useApiChangeLeader.ts
  src/hooks/api/space/members/useApiGetMembers.ts
  src/hooks/api/space/members/useApiKickMembers.ts
  src/hooks/api/template/useGetSimpleTemplateInfo.ts
  src/router/index.tsx
Labels: 🚀 feature

#226 QA) 템플릿 선택 후 경로 수정
  src/app/template/TemplatePage.tsx
  src/component/retrospect/template/list/DefaultTemplateListItem.tsx
  src/config/paths.ts
Labels: 🧹 refactor

#228 leader일 경우만 팀원 추가 가능 하도록 변경
  src/component/space/members/MembersList.tsx
Labels: 🧹 refactor

#239 기본 템플릿에서 커스텀 질문 추가만 한 경우
  pnpm-lock.yaml
  src/component/retrospectCreate/customTemplate/ConfirmEditTemplate.tsx
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/store/retrospect/retrospectCreate.ts
  src/types/retrospectCreate/index.ts
Labels: ✌🏻 bugfix

#241 기본 템플릿 수정여부 필드 반대로 된 문제 수정
  src/component/retrospectCreate/customTemplate/EditQuestions.tsx
  src/types/retrospectCreate/index.ts
Labels: ✌🏻 bugfix

#224 QA 반영
  src/app/info/UserDeletion.tsx
  src/app/space/SpaceViewPage.tsx
  src/component/info/InfoBox.tsx
  src/component/info/UserBox.tsx
  src/component/info/UserManageBox.tsx
  src/hooks/api/user/useDeleteUser.ts
Labels: ✌🏻 bugfix

#242 회고, 템플릿 수정 및 삭제 낙관적 업데이트
  src/hooks/api/retrospect/useApiDeleteRetrospect.ts
  src/hooks/api/retrospect/useApiOptionsGetRetrospects.ts
  src/hooks/api/template/useDeleteCustomTemplate.ts
  src/hooks/api/template/usePatchTemplateTitle.ts
Labels: 🧹 refactor

#266 스페이스 뷰 error Img 와 스페이스 떠나기 텍스트 수정
  src/app/home/RetrospectViewPage.tsx
  src/app/space/SpaceViewPage.tsx
  src/assets/imgs/space/spaceDefaultImg.png
  src/component/home/SpaceOverview.tsx
Labels: ✌🏻 bugfix

#280 hotfix: #269 초대 페이지에서 로그인 성공한 케이스 처리
  src/component/space/join/JoinSpace.tsx
  src/hooks/api/login/usePostAppleToken.ts
  src/hooks/api/login/usePostSignIn.ts
  src/hooks/api/login/usePostSignUp.ts
Labels: ✌🏻 bugfix

#293 hotfix: 분석 페이지 제목, 이름 수정
  src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
  src/component/retrospect/analysis/InsightsBoxSection.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/RetrospectButton.tsx
Labels: ✌🏻 bugfix

#294 hotfix: 분석 페이지 제목, 이름 수정
  src/app/retrospect/analysis/RetrospectAnalysisPage.tsx
  src/component/retrospect/analysis/InsightsBoxSection.tsx
  src/component/space/view/RetrospectBox.tsx
  src/component/space/view/RetrospectButton.tsx
Labels: ✌🏻 bugfix

#300 분석페이지 관련 버그 수정
  src/component/home/SummaryInsightBox.tsx
  src/component/retrospect/analysis/Analysis.tsx
Labels: ✌🏻 bugfix

#304 hotfix: 회고 작성하지 않은 사람 개인 분석 조회
  src/component/retrospect/analysis/Analysis.tsx
  src/component/retrospect/template/card/TemplateCard.tsx
  src/layout/DualToneLayout.tsx
Labels: ✌🏻 bugfix
